apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.label.app }}
spec:
  minUnavailable: {{ .Values.podDisruptionBudget }}
  selector:
    matchLabels:
       {{- include "ui.selectorLabels" . | nindent 6 }}