apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.label.app }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
       APP: assets